-- MySQL Script generated by MySQL Workbench
-- 04/19/14 12:36:34
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JednodnevniIzleti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JednodnevniIzleti` DEFAULT CHARACTER SET utf8 ;
USE `JednodnevniIzleti` ;

-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`Kartica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`Kartica` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(100) NULL,
  PRIMARY KEY (`Id`),
  INDEX ())
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`KorisnikRola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`KorisnikRola` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`Gradovi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`Gradovi` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PostBr` VARCHAR(5) NULL,
  `NazivGrada` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`Korisnik` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(100) NULL,
  `Prezime` VARCHAR(150) NULL,
  `Adresa` VARCHAR(200) NULL,
  `Email` VARCHAR(100) NULL,
  `Username` VARCHAR(20) NULL,
  `Password` VARCHAR(50) NULL,
  `RolaId` INT NULL,
  `GradoviId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `RolaId_idx` (`RolaId` ASC),
  INDEX `fk_Korisnik_Gradovi1_idx` (`GradoviId` ASC),
  CONSTRAINT `RolaId`
    FOREIGN KEY (`RolaId`)
    REFERENCES `JednodnevniIzleti`.`KorisnikRola` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Korisnik_Gradovi1`
    FOREIGN KEY (`GradoviId`)
    REFERENCES `JednodnevniIzleti`.`Gradovi` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`KarticaKorisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`KarticaKorisnik` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `KorisnikId` INT NULL,
  `KarticaId` INT NULL,
  `BrojKartice` VARCHAR(30) NULL,
  `DatumIsteka` DATE NULL,
  PRIMARY KEY (`Id`),
  INDEX `KarticaId` (),
  INDEX `KarticaId_idx` (`KarticaId` ASC),
  INDEX `KorisnikId_idx` (`KorisnikId` ASC),
  CONSTRAINT `KarticaId`
    FOREIGN KEY (`KarticaId`)
    REFERENCES `JednodnevniIzleti`.`Kartica` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `KorisnikId`
    FOREIGN KEY (`KorisnikId`)
    REFERENCES `JednodnevniIzleti`.`Korisnik` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`PonudaVrsta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`PonudaVrsta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(100) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`Ponuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`Ponuda` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(200) NULL,
  `Opis` TEXT NULL,
  `Slika` VARCHAR(200) NULL,
  `BrojKupljenih` INT NULL,
  `VrstaId` INT NULL,
  `Cijena` DECIMAL NULL,
  PRIMARY KEY (`Id`),
  INDEX `VrstaId` (),
  INDEX `VrstaId_idx` (`VrstaId` ASC),
  CONSTRAINT `VrstaId`
    FOREIGN KEY (`VrstaId`)
    REFERENCES `JednodnevniIzleti`.`PonudaVrsta` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`KupljenaPonuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`KupljenaPonuda` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PonudaId` INT NULL,
  `KorisnikId` INT NULL,
  `DatumKupovine` DATE NULL,
  `KorisnikKarticaId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `KorisnikId` (),
  INDEX `KorisnikId_idx` (`KorisnikId` ASC),
  INDEX `PonudaId_idx` (`PonudaId` ASC),
  INDEX `KorisnikKarticaId` (),
  INDEX `KorisnikKarticaId_idx` (`KorisnikKarticaId` ASC),
  CONSTRAINT `KorisnikId`
    FOREIGN KEY (`KorisnikId`)
    REFERENCES `JednodnevniIzleti`.`Korisnik` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PonudaId`
    FOREIGN KEY (`PonudaId`)
    REFERENCES `JednodnevniIzleti`.`Ponuda` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `KorisnikKarticaId`
    FOREIGN KEY (`KorisnikKarticaId`)
    REFERENCES `JednodnevniIzleti`.`KarticaKorisnik` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`Anketa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`Anketa` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Pitanje` VARCHAR(300) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`AnketaOdgovor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`AnketaOdgovor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Odgovor` VARCHAR(200) NULL,
  `AnketaId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `AnketaId` (),
  INDEX `AnketaId_idx` (`AnketaId` ASC),
  CONSTRAINT `AnketaId`
    FOREIGN KEY (`AnketaId`)
    REFERENCES `JednodnevniIzleti`.`Anketa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JednodnevniIzleti`.`AnketaRezultati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JednodnevniIzleti`.`AnketaRezultati` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `OdgovorId` INT NULL,
  `AnketaId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `AnketaId` (),
  INDEX `OdgovorId` (),
  INDEX `AnketaId_idx` (`AnketaId` ASC),
  INDEX `OdgovorId_idx` (`OdgovorId` ASC),
  CONSTRAINT `AnketaId`
    FOREIGN KEY (`AnketaId`)
    REFERENCES `JednodnevniIzleti`.`Anketa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OdgovorId`
    FOREIGN KEY (`OdgovorId`)
    REFERENCES `JednodnevniIzleti`.`AnketaOdgovor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
